print (How to Train Your Dragon)
print("We skim above a dark, wild ocean. The camera turns toward a lone island, Berk.")
print("It is a gigantic shard of rock jutting straight out of the water.")
print("This, is Berk. It's twelve days North of hopeless, and a few degrees South of freezing to death.")
print("It's located solidly on themeridian of misery.")
print("The camera drifts over rolling hills to reveal a small village nestled on an outcropping of sea mounts.")
print("My village. In a word, sturdy.")
print("And it's been here for seven generations, but every single building is new.")
print(" The camera drifts closer, circling.")
print("We have fishing, hunting, and a charming view of the sunsets.")
print("The only problems are the pests.")
print("You see, most places have mice ormosquitos.")
print("We have...Sheep graze peacefully on a hillside.")
