camera=("Is this the real life?")
window=("Is this just fantasy?")
code=("Caught in a landslide,")
year=("No escape from reality")
cloud=("Open your eyes")
print(camera)
print(window)
print(code)
print(year)
print(cloud)